### Part A

In [1]:
#Requried packages

import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib as plt

In [2]:
#load dataset
pat_data = pd.read_csv("CE802_P2_Data.csv")
pat_data.head()

F1  F2      F3        F4  F5       F6      F7      F8       F9       F10  \
0 -4.14   0 -4.8688  2193.600   1  1.32390  3.0866 -4.3687  8269.76 -11.48700   
1 -4.14   1 -7.1000  2048.535   1  1.07749  3.3369 -5.3940  8510.14 -12.95850   
2 -1.14   0 -4.5126  2124.270   0  2.27400  3.7040 -6.5010  8590.68 -14.95800   
3 -1.14   1 -3.8394  2115.450   1  1.78430  3.1030 -4.0891  8023.44 -11.52660   
4 -1.14   0 -3.5670  2430.210   1  1.73450  3.2569 -4.3694  4814.64 -10.67961   

   ...     F12      F13      F14      F15        F16       F17       F18  \
0  ...  44.386  10.9180 -4.56860 -3336.16 -96949.200 -22.59600   8318.43   
1  ...  70.120   9.1844 -5.66460 -3976.80 -96643.400 -16.64400  10232.13   
2  ...  40.332   9.0464 -4.43472 -3658.36 -96928.334 -15.98100   9488.88   
3  ...  95.740   7.5216 -4.43918 -4100.04 -96919.307 -14.86500  10680.63   
4  ...  46.376  10.1860 -6.34600 -3892.74 -96862.720 -10.84545  10308.33   

       F19    F20  Class  
0  -167.29 -12.61  False  
1  1904.61 -13.47   True  
2    56.45 -13.61  False  
3   316.91 -13.31   True  
4   203.60    NaN   True  

[5 rows x 21 columns]

## Cleaning the dataset

In [3]:
#check missing values in dataset
pat_data.columns[pat_data.isna().any()]

Index(['F20'], dtype='object')

In [4]:
#statistical summary for columns
pat_data.describe()

F1           F2           F3           F4           F5  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     -2.661000     0.508000    -5.221917  2283.409178     0.516000   
std       1.500603     0.500186     1.805553   739.616151     0.499994   
min      -4.140000     0.000000   -12.216000 -2639.190000     0.000000   
25%      -4.140000     0.000000    -6.047000  2022.686250     0.000000   
50%      -4.140000     1.000000    -4.664500  2121.900000     1.000000   
75%      -1.140000     1.000000    -3.834900  2323.822500     1.000000   
max      -1.140000     1.000000    -3.244240  7053.810000     1.000000   

                F6           F7           F8            F9          F10  \
count  1000.000000  1000.000000  1000.000000   1000.000000  1000.000000   
mean      1.988608     3.483968    -4.624358   7819.911734   -13.493618   
std       0.901204     0.765717     0.869678   2074.355688     2.708288   
min       1.052990     2.960002    -8.215000  -7725.360000   -24.096000   
25%       1.311825     3.008987    -5.009500   7592.890000   -14.682750   
50%       1.707250     3.178400    -4.369050   8233.040000   -12.641100   
75%       2.357000     3.673675    -3.973325   8620.200000   -11.479425   
max       5.605000     9.039000    -3.702220  16934.640000   -10.626600   

                F11          F12          F13          F14           F15  \
count   1000.000000  1000.000000  1000.000000  1000.000000   1000.000000   
mean   -5625.806305    55.724599     9.001210    -6.140027  -3324.967898   
std      529.018105    20.571395     1.213201     1.706913   1494.941683   
min   -11190.630000    35.424656     7.480112   -13.246000 -11409.360000   
25%    -5661.630000    41.804000     8.033600    -6.870000  -3955.666500   
50%    -5506.475000    49.584000     8.724700    -5.597500  -3702.260000   
75%    -5420.780000    61.325000     9.671500    -4.878000  -3163.260000   
max    -2478.630000   198.980000    15.068000    -4.342580   6636.640000   

                 F16          F17           F18          F19         F20  
count    1000.000000  1000.000000   1000.000000  1000.000000  500.000000  
mean   -97016.681422   -13.665798   9760.996246   337.651510  -12.870100  
std      3376.459608     2.699756   1534.747192   702.890861    1.155836  
min   -202457.800000   -23.946000  -2011.470000 -3392.390000  -16.250000  
25%    -96958.020000   -15.114750   9358.830000    56.532500  -13.645000  
50%    -96919.362000   -12.794400   9793.864500   199.300000  -12.850000  
75%    -96881.730000   -11.560725  10167.630000   430.985000  -12.070000  
max    -89483.800000   -10.744140  20200.530000  5152.610000   -9.510000

since the difference b/w **mean** and **median** for **F20** column is very low, we will be replacing the mean value for **NaN**.

In [5]:
# Replacing the missing values with mean for Nan in F20 column

pat_data['F20'] = pat_data['F20'].fillna(pat_data['F20'].mean())

In [6]:
#split dataset

p = pat_data.iloc[:, :-1].values   #Predictors
r = pat_data.iloc[:, -1].values    #Target

In [7]:
#Convert target varibale from string to numeric

#import package
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

r = encoder.fit_transform(r)

## Standardise the variables in dataset

In [8]:
# import library
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

p = scaler.fit_transform(p)

#spliting the dataset into training and testing

#import library
from sklearn.model_selection import StratifiedKFold

#Assign parameters
sf_fold = StratifiedKFold(n_splits=7, shuffle=True, random_state=21)

for training_index, testing_index in sf_fold.split(p,r):
    p_training, p_testing = p[training_index], p[testing_index]
    r_training, r_testing = r[training_index], r[testing_index]

## 1. Decision Tree Classifier

**Training and Predicting for the Dataset**

In [9]:
#import decision tree classifier
from sklearn.tree import DecisionTreeClassifier

decision_tc = DecisionTreeClassifier(random_state=456)

#fit model to dataset for training
decision_tc.fit(p_training, r_training)

#Result for testing dataset
r_result = decision_tc.predict(p_testing)

**Running the model on test Dataset**

In [10]:
#import library
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Result of test dataset
print(f"Accuracy Score of Decision Tree model: {accuracy_score(r_testing, r_result)}")
print(f"Confusion Matrix of Decision Tree model:\n {confusion_matrix(r_testing, r_result)}")
print(f"Classification Report of Decision Tree model:\n {classification_report(r_testing, r_result)}")

Accuracy Score of Decision Tree model: 0.852112676056338
Confusion Matrix of Decision Tree model:
 [[63  8]
 [13 58]]
Classification Report of Decision Tree model:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86        71
           1       0.88      0.82      0.85        71

    accuracy                           0.85       142
   macro avg       0.85      0.85      0.85       142
weighted avg       0.85      0.85      0.85       142



## 2. Logistic Regression

**Training and predicting the dataset for Logistic Regression**

In [11]:
#Import logistic regression classifier
from sklearn.linear_model import LogisticRegression

logistic_rc = LogisticRegression(random_state=689)

#fit model to dataset for training
logistic_rc.fit(p_training, r_training)

#Result for testing dataset
r_log_result = logistic_rc.predict(p_testing)

**Running the model on test Data**

In [12]:
#Result of test dataset from logistic regression
print(f"Accuracy Score of Logistic Regression model: {accuracy_score(r_testing, r_log_result)}")
print(f"Confusion Matrix of Logistic Regression model:\n {confusion_matrix(r_testing, r_log_result)}")
print(f"Classification Report of Logistic Regression model:\n {classification_report(r_testing, r_log_result)}")

Accuracy Score of Logistic Regression model: 0.7183098591549296
Confusion Matrix of Logistic Regression model:
 [[56 15]
 [25 46]]
Classification Report of Logistic Regression model:
               precision    recall  f1-score   support

           0       0.69      0.79      0.74        71
           1       0.75      0.65      0.70        71

    accuracy                           0.72       142
   macro avg       0.72      0.72      0.72       142
weighted avg       0.72      0.72      0.72       142



## 3.  Random Forest Classification

**Training and predicting the dataset for  Random Forest Classification**

In [17]:
#Import library
from sklearn.ensemble import RandomForestClassifier
import warnings

warnings.filterwarnings('ignore')

random_fr = RandomForestClassifier(random_state=669)

#fit model to dataset for training
random_fr.fit(p_training, r_training)

#Result for testing dataset
r_nbys_result = random_fr.predict(p_testing)

**Running the model on test Data**

In [18]:
#Result of test dataset from RFR
print(f"Accuracy Score of Random Forest Regression model: {accuracy_score(r_testing, r_nbys_result)}")
print(f"Confusion Matrix of Random Forest Regression model:\n {confusion_matrix(r_testing, r_nbys_result)}")
print(f"Classification Report of Random Forest Regression model:\n {classification_report(r_testing, r_nbys_result)}")

Accuracy Score of Random Forest Regression model: 0.9014084507042254
Confusion Matrix of Random Forest Regression model:
 [[64  7]
 [ 7 64]]
Classification Report of Random Forest Regression model:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90        71
           1       0.90      0.90      0.90        71

    accuracy                           0.90       142
   macro avg       0.90      0.90      0.90       142
weighted avg       0.90      0.90      0.90       142



## 4. K-Nearest Neighbors (KNN)

**Training and predicting the dataset for KNN**

In [15]:
#Import library
from sklearn.neighbors import KNeighborsClassifier

knn_r = KNeighborsClassifier(algorithm='auto', leaf_size=80, metric='minkowski', 
                             metric_params=None, n_jobs=None,
                             n_neighbors=80, p=2, weights='uniform')

#fit model to dataset for training
knn_r.fit(p_training, r_training)

#Result for testing dataset
r_knn_result = knn_r.predict(p_testing)

**Running the model on test Data**

In [16]:
#Result of test dataset from KNN
print(f"Accuracy Score of K-Nearest Neighbors model: {accuracy_score(r_testing, r_knn_result)}")
print(f"Confusion Matrix of K-Nearest Neighbors model:\n {confusion_matrix(r_testing, r_knn_result)}")
print(f"Classification Report of K-Nearest Neighbors model:\n {classification_report(r_testing, r_knn_result)}")

Accuracy Score of K-Nearest Neighbors model: 0.7112676056338029
Confusion Matrix of K-Nearest Neighbors model:
 [[55 16]
 [25 46]]
Classification Report of K-Nearest Neighbors model:
               precision    recall  f1-score   support

           0       0.69      0.77      0.73        71
           1       0.74      0.65      0.69        71

    accuracy                           0.71       142
   macro avg       0.71      0.71      0.71       142
weighted avg       0.71      0.71      0.71       142



### Part B

In [17]:
# HERE YOU WILL USE THIS TEMPLATE TO SAVE THE PREDICTIONS ON THE TEST SET

# Load the test data
test_df = pd.read_csv('CE802_P2_Test.csv')

# Make sure you work on a copy
test_data = test_df.iloc[:,:-1].copy()

#Replacing the NA value
test_data['F20'] = test_data['F20'].fillna(test_data['F20'].mean())

#scale the values
test_data = scaler.transform(test_data)


predicted = decision_tc.predict(test_data)

# Replace the last (empty) column with your prediction
test_df.iloc[:,-1] = predicted

# Save to the destination file
test_df.to_csv('CE802_P2_Test_Predictions.csv', index=False, float_format='%.8g')

# IMPORTANT!! Make sure only the last column has changed
assert pd.read_csv('CE802_P2_Test.csv').iloc[:,:-1].equals(pd.read_csv('CE802_P2_Test_Predictions.csv').iloc[:,:-1])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
C:\Users\HP\AppData\Local\Temp\ipykernel_10980\3963882432.py:19: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  test_df.iloc[:,-1] = predicted
